debug: true

server:
  port: 9001

spring:
  application:
    name: zk-service
  cloud:
    zookeeper:
      connect-string: www.azhu.work:2181

management:
  health:
    zookeeper:
      enabled: true