demo:
  service:
    version: 1.0.0
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20881
  provider:
    timeout: 1000
  registry:
    address: zookeeper://localhost:2181
server:
  port: 9011
spring:
  application:
    name: dubbo-provider
