server:
  port: 8888

spring:
  application:
    name: template-config
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:9004

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
